name: learn-github-actions
on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker Tag Test
        id: generate-docker-tag-test
        uses: actions/github-script@v4
        with:
          script: |
            const tagBase = `${process.env['DOCKER_USERNAME']}/${context.repo.repo}`

            const tags =  [`${tagBase}:${context.sha.substring(0, 7)}`, `${tagBase}:latest`]
            core.info('Hell!')
            core.setOutput('SELECTED_COLOR', 'green');
            return {tags: tags.join(','), latest:tags[0]}

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Generate Docker Tag
        run: echo ${{ steps.generate-docker-tag-test.outputs.result }}
    outputs:
      SELECTED_COLOR
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ${{ fromJSON(steps.generate-docker-tag-test.outputs.result).tags }}


  run-on-docker:
    needs: [ docker ]
    runs-on: ubuntu-latest

    steps:
      - name: Run Python
        run: echo ${{ toJSON(needs.docker) }}
# .steps.generate-docker-tag-test.outputs.result
