name: learn-github-actions
on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: image-to-run:latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}:/home/jovyan/app
          image: image-to-run:latest
#          run: papermill --cwd app/notebooks app/notebooks/HuggingFace.ipynb app/notebooks/HuggingFaceOut.ipynb
          run: whoami
