name: learn-github-actions
on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: image-to-run:latest

      - name: Run
        uses: addnab/docker-run-action@v3
        with:
          image: image-to-run:latest
          run: python --version
