name: learn-github-actions
on: [ push ]


jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker Tag Test
        id: generate-docker-tag-test
        uses: actions/github-script@v4
        with:
          script: console.log(context)


      - name: Generate Docker Tag
        id: generate-docker-tag
        uses: actions/github-script@v4
        with:
          script: return context.sha.substring(0, 7)
          result-encoding: string

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/github-actions-test:latest,${{ secrets.DOCKER_USERNAME }}/github-actions-test:${{steps.generate-docker-tag.outputs.result}}


  run-on-docker:
    needs: [docker]
    runs-on: ubuntu-latest
    container: rlancer/github-actions-test:latest
    steps:
      - name: Run Python
        run: python --version

