name: learn-github-actions
on: [ push ]

jobs:
  sha:
    name: SHA
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.sha }}"

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rlancer/github-actions-test:latest,rlancer/github-actions-test:anewtag

  run-on-docker:
    needs: [docker]
    runs-on: ubuntu-latest
    container: rlancer/github-actions-test:latest
    steps:
      - name: Run Python
        run: python --version

